name: Deploy Infrastructure

on:
  workflow_dispatch:  # manual trigger
  push:
    paths:
      - "infra-terraform/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Debug: verify folder structure
      - name: Debug workspace
        run: |
          pwd
          ls -R

      # 3️⃣ Get org-level runner token
      - name: Get org-level runner token
        id: runner-token
        run: |
          token=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/polyglot-microservices-org/actions/runners/registration-token \
            | jq -r .token)
          echo "runner_token=$token" >> $GITHUB_OUTPUT

      # 4️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # 5️⃣ Terraform Init
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd infra-terraform/terraform
          terraform init

      # 6️⃣ Terraform Apply
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd infra-terraform/terraform
          terraform apply -auto-approve \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="runner_token=${{ steps.runner-token.outputs.runner_token }}" \
            -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
