name: Destroy Infrastructure

on:
  workflow_dispatch:  # manual trigger only

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Configure AWS CLI
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      # 5️⃣ Terraform Destroy
      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="gh_pat=${{ secrets.GH_PAT }}" \
            -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"